allowBuilds:
  '@firebase/util': true
  '@scarf/scarf': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js-pure: true
  protobufjs: true
  sharp: false
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
